<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Server\bin\Debug\net9.0\appsettings.Development.example.json" />
    <_ContentIncludedByDefault Remove="Server\bin\Debug\net9.0\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="Server\bin\Debug\net9.0\appsettings.json" />
    <_ContentIncludedByDefault Remove="Server\bin\Debug\net9.0\Server.deps.json" />
    <_ContentIncludedByDefault Remove="Server\bin\Debug\net9.0\Server.runtimeconfig.json" />
    <_ContentIncludedByDefault Remove="Server\bin\Debug\net9.0\Server.staticwebassets.endpoints.json" />
    <_ContentIncludedByDefault Remove="Server\obj\AmazoniaApi.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="Server\obj\Debug\net9.0\Server.sourcelink.json" />
    <_ContentIncludedByDefault Remove="Server\obj\Debug\net9.0\staticwebassets.build.endpoints.json" />
    <_ContentIncludedByDefault Remove="Server\obj\Debug\net9.0\staticwebassets.build.json" />
    <_ContentIncludedByDefault Remove="Server\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="Server\obj\project.packagespec.json" />
    <_ContentIncludedByDefault Remove="Server\obj\Server.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="Core\bin\Debug\net9.0\Core.deps.json" />
    <_ContentIncludedByDefault Remove="Core\bin\Debug\net9.0\Core.runtimeconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bot\" />
  </ItemGroup>

</Project>
